longshot test

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -46,7 +46,7 @@ jobs:
     # Notes on Cache: 
     # https://docs.docker.com/build/ci/github-actions/examples/#inline-cache
     - name: Build Container
-      if: ${{ github.repository != 'helxplatform/appstore-sockets' }}
+      if: ${{ github.repository != 'helxplatform/appstore-sockets' || 'helxplatform/gitea-assist'  }}
       uses: docker/build-push-action@v6
       with:
         context: .
@@ -56,6 +56,32 @@ jobs:
           ${{ github.repository }}:test_${{ steps.branch.outputs.GHR }}
         cache-from: type=registry,ref=${{ github.repository }}:buildcache
         cache-to: type=registry,ref=${{ github.repository }}:buildcache,mode=max
+
+    - name: Build Container for gittea
+      if: ${{ github.repository == 'helxplatform/gitea-assist'  }}
+      env:
+        REGISTRY_NAME: containers.renci.org/helxplatform
+        CONTAINER_NAME: gitea-assist:latest
+      run: |
+       
+        go version || (echo "Go not found, installing..." && sudo apt-get update && sudo apt-get install -y golang)
+        
+        
+        echo "Building Go application..."
+        go build
+
+        echo "Running Go tests..."
+        go fmt ./...
+        go vet ./...
+        go test ./...
+
+        echo "Building Docker image..."
+        docker build --platform=linux/amd64 -t $REGISTRY_NAME/$CONTAINER_NAME .
+
+      
+        echo "Logging in and pushing Docker image..."
+        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
+        docker push $REGISTRY_NAME/$CONTAINER_NAME
 
     - name: Build Server Container for Appstore-Sockets
       if: ${{ github.repository == 'helxplatform/appstore-sockets' }}
